### ISSUE TITLE
Using Dbt to create datasets as folders of files (ex: CSV, ..) in Dremio

### ISSUE THREAD

**Issue by amirbtb** [fabrice-etanchaud/dbt-dremio#11]
Hello,

I have connected Dremio to a S3 datalake (minIO) and I am using Dremio REST API to convert folders of csv files to datasets. I would like to know if it is possible to read and write datasets materialized as files using dbt. 

I tried to use the dbt-dremio adapter but I couldn't make it work : Can I use my datalake as a database and recursive folders as schemas ? 

_Thank you for contributing to the dbt community with your adapter. It is really nice to be able to integrate Dremio and dbt._

**Comment by fabrice-etanchaud** [comment]
Hi @amirbtb, better late than never...
Playing with input/output table formats, I managed to define a dbt source on a folder containing a hierarchy of files (json, text...).
So yes, it will be possible, as soon as I implement these table formats on input (select from TABLE(path(format options)), or output (create table path STORE AS(format options) as select...)
Best regards

**Comment by fabrice-etanchaud** [comment]
@amirbtb , this should work in the latest dbt-dremio version.
Let's keep in touch.
