### ISSUE TITLE
Dremio dbt adapter unable to identify mixed case sources in dremio

### ISSUE THREAD

**Issue by abachu** [fabrice-etanchaud/dbt-dremio#17]
I do see that in adapters.sql file you're converting table_catalog, table_name, column_name to lower case while querying from information schema? Is there a reason you're doing that? I have everything in camel case and when I do dbt run, I get an error saying. How do I override that lower functionality so I can capture all cases? 

```
 When searching for a relation, dbt found an approximate match. Instead of guessing 
  which relation to use, dbt will move on.
```

**Comment by fabrice-etanchaud** [comment]
Hi @abachu , thank you for giving dbt-dremio a try.
According to [dremio data sources](https://docs.dremio.com/data-sources/) Case-sensitive source data file/table names or columns are not supported, and may lead to unanticipated results.
Which source type are you using ?

Best,
Fabrice

**Comment by abachu** [comment]
We're currently using S3 and Postgres as sources.

**Comment by fabrice-etanchaud** [comment]
Hi @abachu , the new version will not lowercase the identifiers anymore, please, tell me if it gives better results in your use cases.
Best,
