### ISSUE TITLE
Spaces and subfolders

### ISSUE THREAD

**Issue by spireitepaul** [fabrice-etanchaud/dbt-dremio#18]
Hi,

I have to be honest.... I'm struggling with this one.

I have no problem pushing into a space,  but I can't seem to get anywhere trying to push 'view' creatin in a sublevel (folder of a space)

Taking your test installation, my_first_dbt, and my_second.....

These create in the space 'dbt'

What needs to be changed to get 'my_second....'   to be created into dbt.reports 'folder' ?

It must be something simple I'm missing?

Thanks
Paul.

**Comment by fabrice-etanchaud** [comment]
Hi @spireitepaul , thank you for giving dbt a try on dremio.
There is no such thing as a CREATE SCHEMA in dremio for the time being.
So  the [space structure must be created beforehand](https://github.com/fabrice-etanchaud/dbt-dremio#schemas)
I was hoping to see santa claus put this feature in dremio v20...
A way to offer that is to create a web API based version of the adapter.
Hoping to have time for the adapter in early february.
Best regards from french west coast !

**Comment by spireitepaul** [comment]
Hi Fabrice,

I thought that was pretty much the case.

So, in the dbt_project, I had 

+schema: no_schema for model/example.

and for model/example2

+schema: sublevel1

I had a battle also with trying to overwrite the schema as I found that I was getting a generated schema name of no_schema_sublevel1, when I just wanted sublevel1 for model/example2 

For the record of anyone else looking, in the macros directory OF THE PROJECT  created a get_custom_schema.sql file containing.

_{% macro generate_schema_name(custom_schema_name, node) -%}
    
    {{ custom_schema_name }}
{%- endmacro %}_


which achieved what I wanted.

**Comment by fabrice-etanchaud** [comment]
Hi @spireitepaul ,

the documentation might need to be more explicit, I will try to rewrite it.
In the last chapter, there is a link to the [custom schema and database macros](https://github.com/fabrice-etanchaud/dbt-dremio#managed-or-unmanaged-target) I propose to use in combination with the 'environment' notion.
