### ISSUE TITLE
dbt-dremio fails to read schema when run against dremio 19.0.0+

### ISSUE THREAD

**Issue by Baoqi** [fabrice-etanchaud/dbt-dremio#22]
For dremio versions above 19.0.0, the sys.reflections table changed some column names:

in commit: https://github.com/dremio/dremio-oss/commit/fa1f8adac08ff356e25c69971085aad239bfa1d4
   for file:  sabot/kernel/src/main/java/com/dremio/exec/store/sys/accel/AccelerationListManager.java

From the source code, it seems:
    -   "name" column in "sys"."reflections" table is renamed to "reflection_name"
    -  "dataset" column in "sys"."reflections" table is renamed to  "dataset_name"
    -  2 new additional columns are added:  "dataset_id" and "dataset_type"
 
Currently, I temporally modify my python's site-packages/dbt/include/dremio/macros/adapters.sql ,   around " from sys.reflections",  change column "dataset" to "dataset_name" and change "name" to "relfection_name".  

After that change, dbt-dremio can work against dremio 19.0.0+, but this change is definitely a temporal fix for me (since it will fail against dremio 18.0.0).  We may want to fix this by making both version of dremio works. 

Thanks,
Baoqi

**Comment by awaschick** [comment]
I've recently updated to Dremio 20.1, and the breaking changes in the system tables' schemata have brought more fun to the table.  I have built three macros to allow my existing dbt projects to properly execute, attached here: 
[Dremio 20.1 Updated dbt macros.zip](https://github.com/fabrice-etanchaud/dbt-dremio/files/8074647/Dremio.20.1.Updated.dbt.macros.zip)

**Comment by fabrice-etanchaud** [comment]
Sorry for the very late answer, I am responsible for yearly accounting processing in my current position, and had no brain time to give to the project. That should be better now. Once again, sorry.

**Comment by awaschick** [comment]
No need to apologize, we appreciate your ongoing contribution!  Thanks for the updates and we'll give the new version a spin.
