### ISSUE TITLE
New reflection creation method example?

### ISSUE THREAD

**Issue by aaroncwhite** [fabrice-etanchaud/dbt-dremio#29]
@fabrice-etanchaud prior releases of `dbt-dremio` created reflections by creating a secondary model with something like this in the contents:
```
-- depends_on: {{ ref('some_table') }}
{{
    config(
        materialized='raw_reflection',
        dataset='some_table'
    )
}}
```

It seems that in the latest release of the plugin, this method has changed per [these details](https://github.com/fabrice-etanchaud/dbt-dremio#reflection).  Could you please provide an example code beyond the final mention of the `-- depends_on: {{ ref('some_table') }}`?  I have found other mentions to reflections being mapped to the `materializedview` materialization setting; however, I have been unable to figure out the proper settings on my own.

**Comment by fabrice-etanchaud** [comment]
and by the way, `materializedview` is the type of Relation associated with reflections (the database.schema.identifier model physical localisation) ;-)

**Comment by spireitepaul** [comment]
Hi @fabrice-etanchaud 

The above example is to me - as clear as mud...  not least beacuse for me, it doesn't work.


The SQL file  has only the -- depends on   line,  yet dbt seems to be trying to execute as a create or replace view for it.

The dbt project file has  (indented appropriately)

nbbulkref_raw:
      +materialized: reflection
      +reflection_type: raw
      +arrow_cache: true




What have I missed?

**Comment by fabrice-etanchaud** [comment]
Hi @spireitepaul , are you using the latest dbt-dremio version ?

Here is a working example : 

file adherents_reflect.sql : 

`-- depends_on: {{ ref('adherents') }}`

in dbt_project.yml : 
```
adherents_reflect:
          +materialized: reflection
          +reflection_type: raw
```

and in the log : 

```

/* {"app": "dbt", "dbt_version": "1.0.6", "profile_name": "consultation", "target_name": "unmanaged", "node_id": "model.lcbft_iso.adherents_reflect"} */

  alter dataset  "@fabrice_etanchaud"."dbt"."adherents"
    create raw reflection "adherents_reflect"
    using
      display ("numero_adherent","est_nationalite_etrangere","est_resident_etranger","est_resident_fiscal_etranger","est_remedie","est_pli_non_distribuable","est_ppe","est_gda","est_fin","est_protege_juridiquement","mineur","taux_remediation","nationalite","protection_juridique","date_naissance","age","etat")
```

**Comment by spireitepaul** [comment]
Hi @fabrice-etanchaud 

Yep, using the latest,

I think maybe this is a nesting issue of some sort...

What level should this be indented to under the models


the tree as i understand it should be models/<profilename>/<modelname> 

so does the _reflect indent AT the same level as <modelname> or indent WITHIN <modelname>

or somewhere else?


To me, it's not clear....   the docs don't seem to cover this, (I apologies if i missed it).

**Comment by fabrice-etanchaud** [comment]
@spireitepaul , can you share your dbt_project.yml file ?

**Comment by spireitepaul** [comment]
> @spireitepaul , can you share your dbt_project.yml file ?
[dbt_project.txt](https://github.com/fabrice-etanchaud/dbt-dremio/files/9041850/dbt_project.txt)

**Comment by fabrice-etanchaud** [comment]
So your 'cro' project files should be something like : 

models/cro.sql (a view) or models/cro/\*/\*.sql (views)
models/nbbulkref_reflection.sql (a reflection)

I can find any indentation problem.

It seems to have a problem between the reflection location and the configuration.

if you don't move your reflection, maybe you should try the following config : 

```
models:
  cro:
    # Config indicated by + and applies to all files under models/cro/
    # models/cro
    cro:
      +materialized: view
      +schema: no_schema
      nbbulkref:    
        nbbulkref_reflection:
          +materialized: reflection
          +reflection_type: raw
          +arrow_cache: true
```
or try moving nbbulkref_reflection.sql to models/cro/

tell me if it helps

**Comment by fabrice-etanchaud** [comment]
Hi @spireitepaul , did it help ?

**Comment by fabrice-etanchaud** [comment]
Hi @spireitepaul , I am going to close this issue, feel free to contact me again if needed.
Best,

**Comment by aaroncwhite** [comment]
I know this issue is closed, but just leaving this here in case it's helpful.  The examples that @fabrice-etanchaud left show setting the parameters in your config file(s).  You can also do this in a model file. 

```
/* models/some_model_reflection.sql */
-- depends_on: {{ ref('some_model') }}
{{
    config(
        materialized='reflection',
        arrow_cache='true',
        reflection_type='raw', 
        dataset='some_model'
	)
}}
```

I have to do this for many raw sources to reduce latency with the upstream source, so wrote it into a macro:

```
/* Make a reflection object as a "model"

Arguments:
    tbl (str): the upstream model name that should be reflected

Environment Variable:
    DBT_REFLECTIONS: if 1, then reflections are run.  By default, this runs no reflections then. (keeps dev spaces clean)
*/

{% macro make_reflection(tbl) -%}
-- depends_on: {{ ref(tbl) }}
{{
    config(
        materialized='reflection',
        arrow_cache='true',
        reflection_type='raw', 
        dataset=tbl,
        enabled= env_var('DBT_REFLECTIONS', '0') == '1'
	)
}}
{%- endmacro %}
```

Then my `some_model_reflection.sql` file just has `{{ make_reflection('some_table') }}`.  It might not work for everyone, but lets me keep things consolidated (and also only fire reflections on prod deployments using the env var).

**Comment by spireitepaul** [comment]
@aaroncwhite 

You sir are a hero...

Your stuff to put in the model file  was the answer for me...

-- depends_on: {{ ref('some_model') }}
{{
    config(
        materialized='reflection',
        arrow_cache='true',
        reflection_type='raw', 
        dataset='some_model'
	)
}}

@fabrice-etanchaud   I had to move to a different project, but came back to this.

The .yml changes just don't work for me, having been over them with a fine tooth comb.

What dbt-dremio was doing was trying to issue a create/replace view statement on the reflection.sql model, which is clearly wrong.  I couldn't get past it...
