### ISSUE TITLE
dbt version 0.19.0rc1 introduced a breaking change: SQLConnectionManager.get_status renamed to get_response

### ISSUE THREAD

**Issue by vondras** [fabrice-etanchaud/dbt-dremio#9]
Per the [changelog](https://github.com/fishtown-analytics/dbt/blob/dev/margaret-mead/CHANGELOG.md#breaking-changes), dbt version [0.19.0rc1](https://github.com/fishtown-analytics/dbt/tree/v0.19.0rc1) introduced a breaking change to the `SQLConnectionManager` class which causes the following error when using the dbt-dremio adapter:

```
Can't instantiate abstract class DremioConnectionManager with abstract methods get_response
```

The `SQLConnectionManager.get_status()` abstract method was renamed `SQLConnectionManager.get_response()` in [PR #2961](https://github.com/fishtown-analytics/dbt/pull/2961). Python throws an error because the `DremioConnectionManager` class doesn't implement this new method.

**Comment by fabrice-etanchaud** [comment]
Hi @vondras , thank you ! I added a few lines alongside your PR, there was a breaking change in the seed materialization. Finally get_status was completly deleted, as the new version will be only 0.19 compliant.

Once again, thank you for contributing !
